using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Waf.FileHashGenerator.Presentation.DesignData.SampleAboutViewModel.#ProductName")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Waf.FileHashGenerator.Presentation.DesignData.SampleAboutViewModel.#Version")]
[assembly: SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "Waf.FileHashGenerator.Presentation.App")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Waf.FileHashGenerator.Presentation.Views.FileHashListView.#OnDragOver(System.Windows.DragEventArgs)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Waf.FileHashGenerator.Presentation.Views.FileHashListView.#OnDrop(System.Windows.DragEventArgs)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Waf.FileHashGenerator.Presentation.Converters.EnumToFontWeightConverter.#Convert(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope = "member", Target = "Waf.FileHashGenerator.Presentation.DesignData.MockSettingsService.#RaiseErrorOccurred(System.Waf.Applications.Services.SettingsErrorEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Waf.FileHashGenerator.Presentation.App.OnStartup(System.Windows.StartupEventArgs)")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Waf.FileHashGenerator.Presentation.Converters.IsHashValidToImageSourceConverter.Convert(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Waf.FileHashGenerator.Presentation.Converters.IsHashValidToTextConverter.Convert(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
