//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waf.FileHashGenerator.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waf.FileHashGenerator.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the about dialog.
        ///
        ///F1.
        /// </summary>
        public static string AboutToolTip {
            get {
                return ResourceManager.GetString("AboutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64.
        /// </summary>
        public static string Base64 {
            get {
                return ResourceManager.GetString("Base64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this file..
        /// </summary>
        public static string CloseFile {
            get {
                return ResourceManager.GetString("CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        public static string Expected {
            get {
                return ResourceManager.GetString("Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a file or drop files here to generate the {0} hash values..
        /// </summary>
        public static string GenerateHashInstruction {
            get {
                return ResourceManager.GetString("GenerateHashInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hash.
        /// </summary>
        public static string HashHeader {
            get {
                return ResourceManager.GetString("HashHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hash Mode.
        /// </summary>
        public static string HashModeHeader {
            get {
                return ResourceManager.GetString("HashModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the expected hash value if you want to verify the hash value..
        /// </summary>
        public static string HashNotCompared {
            get {
                return ResourceManager.GetString("HashNotCompared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid. The calculated hash value is different to the expected hash value..
        /// </summary>
        public static string HashNotValid {
            get {
                return ResourceManager.GetString("HashNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid. The calculated hash value is identical to the expected hash value..
        /// </summary>
        public static string HashValid {
            get {
                return ResourceManager.GetString("HashValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal.
        /// </summary>
        public static string Hexadecimal {
            get {
                return ResourceManager.GetString("Hexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5.
        /// </summary>
        public static string MD5 {
            get {
                return ResourceManager.GetString("MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the MD5 hash generation mode..
        /// </summary>
        public static string MD5ToolTip {
            get {
                return ResourceManager.GetString("MD5ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework.
        /// </summary>
        public static string NetFramework {
            get {
                return ResourceManager.GetString("NetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a file to calculate the hash value.
        ///
        ///Ctrl+O.
        /// </summary>
        public static string OpenToolTip {
            get {
                return ResourceManager.GetString("OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1.
        /// </summary>
        public static string Sha1 {
            get {
                return ResourceManager.GetString("Sha1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the SHA1 hash generation mode..
        /// </summary>
        public static string Sha1ToolTip {
            get {
                return ResourceManager.GetString("Sha1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA256.
        /// </summary>
        public static string Sha256 {
            get {
                return ResourceManager.GetString("Sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the SHA256 hash generation mode..
        /// </summary>
        public static string Sha256ToolTip {
            get {
                return ResourceManager.GetString("Sha256ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA512.
        /// </summary>
        public static string Sha512 {
            get {
                return ResourceManager.GetString("Sha512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the SHA512 hash generation mode..
        /// </summary>
        public static string Sha512ToolTip {
            get {
                return ResourceManager.GetString("Sha512ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
