//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waf.FileHashGenerator.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waf.FileHashGenerator.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the about dialog.
        ///
        ///F1.
        /// </summary>
        public static string AboutToolTip {
            get {
                return ResourceManager.GetString("AboutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 Encoding.
        /// </summary>
        public static string Base64Encoding {
            get {
                return ResourceManager.GetString("Base64Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this file..
        /// </summary>
        public static string CloseFile {
            get {
                return ResourceManager.GetString("CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string CopyMenu {
            get {
                return ResourceManager.GetString("CopyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the selection and put it on the Clipboard.
        ///
        ///Ctrl+C.
        /// </summary>
        public static string CopyToolTip {
            get {
                return ResourceManager.GetString("CopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Expected.
        /// </summary>
        public static string ExpectedMenu {
            get {
                return ResourceManager.GetString("ExpectedMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        public static string Formatting {
            get {
                return ResourceManager.GetString("Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a file or drop files here to generate the {0} hash values..
        /// </summary>
        public static string GenerateHashInstruction {
            get {
                return ResourceManager.GetString("GenerateHashInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hash.
        /// </summary>
        public static string HashHeader {
            get {
                return ResourceManager.GetString("HashHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hash Mode.
        /// </summary>
        public static string HashModeHeader {
            get {
                return ResourceManager.GetString("HashModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the expected hash value if you want to verify the hash value..
        /// </summary>
        public static string HashNotCompared {
            get {
                return ResourceManager.GetString("HashNotCompared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid. The calculated hash value is different to the expected hash value..
        /// </summary>
        public static string HashNotValid {
            get {
                return ResourceManager.GetString("HashNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid. The calculated hash value is identical to the expected hash value..
        /// </summary>
        public static string HashValid {
            get {
                return ResourceManager.GetString("HashValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal.
        /// </summary>
        public static string Hexadecimal {
            get {
                return ResourceManager.GetString("Hexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MD5.
        /// </summary>
        public static string MD5Menu {
            get {
                return ResourceManager.GetString("MD5Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the MD5 hash generation mode..
        /// </summary>
        public static string MD5ToolTip {
            get {
                return ResourceManager.GetString("MD5ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework.
        /// </summary>
        public static string NetFramework {
            get {
                return ResourceManager.GetString("NetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string OpenMenu {
            get {
                return ResourceManager.GetString("OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a file to calculate the hash value.
        ///
        ///Ctrl+O.
        /// </summary>
        public static string OpenToolTip {
            get {
                return ResourceManager.GetString("OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string PasteMenu {
            get {
                return ResourceManager.GetString("PasteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the contents of the Clipboard.
        ///
        ///Ctrl+V.
        /// </summary>
        public static string PasteToolTip {
            get {
                return ResourceManager.GetString("PasteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SHA1.
        /// </summary>
        public static string Sha1Menu {
            get {
                return ResourceManager.GetString("Sha1Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the SHA1 hash generation mode..
        /// </summary>
        public static string Sha1ToolTip {
            get {
                return ResourceManager.GetString("Sha1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA_256.
        /// </summary>
        public static string Sha256Menu {
            get {
                return ResourceManager.GetString("Sha256Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the SHA256 hash generation mode..
        /// </summary>
        public static string Sha256ToolTip {
            get {
                return ResourceManager.GetString("Sha256ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA_512.
        /// </summary>
        public static string Sha512Menu {
            get {
                return ResourceManager.GetString("Sha512Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the SHA512 hash generation mode..
        /// </summary>
        public static string Sha512ToolTip {
            get {
                return ResourceManager.GetString("Sha512ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Application Error
        ///
        ///{0}.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the view settings..
        /// </summary>
        public static string ViewToolTip {
            get {
                return ResourceManager.GetString("ViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
