name: FileHashGenerator
on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/**'
jobs:
  build:
    name: 🔨 Build and test
    runs-on: windows-latest
    steps:
    - name: 📥 Check-out
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: ⚙️ Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10'

    - name: 🔐 Prepare certificate
      shell: pwsh
      env:
        MSStoreLocalCert64: ${{ secrets.MS_STORE_LOCAL_CERT64 }}
      run: |
        [IO.File]::WriteAllBytes((Join-Path $pwd "src/FileHashGenerator/FileHashGenerator.WinUI" "MSStoreLocalCert.p12"), [Convert]::FromBase64String($env:MSStoreLocalCert64))

    - name: 📦 Create MSIX x64
      run: |
        cd src/FileHashGenerator/FileHashGenerator.WinUI
        dotnet publish -c Release -p:Platform=x64 -p:RuntimeIdentifier=win-x64 -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=true -p:PackageCertificateKeyFile=MSStoreLocalCert.p12 -p:AppxPackageDir=AppPackages/x64/

    - name: 📦 Create MSIX arm64
      run: |
        cd src/FileHashGenerator/FileHashGenerator.WinUI
        dotnet publish -c Release -p:Platform=arm64 -p:RuntimeIdentifier=win-arm64 -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=true -p:PackageCertificateKeyFile=MSStoreLocalCert.p12 -p:AppxPackageDir=AppPackages/arm64/

    - name: 📦 Upload MSIX
      uses: actions/upload-artifact@v6
      with:
        name: FileHashGeneratorWindows
        if-no-files-found: error
        path: |
          ./**/AppPackages/**/*.msix

    - name: 🧪 Test
      run: |
        cd ./src/FileHashGenerator
        dotnet test --solution ./FileHashGenerator.slnx --coverage
