name: .NET

on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/**'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2    
    - name: NuGet clear
      run: dotnet nuget locals all --clear
    - name: Build
      run: dotnet build ./src/FileHashGenerator/FileHashGenerator.sln -c Release
    - name: Test
      run: dotnet test ./src/FileHashGenerator/FileHashGenerator.sln -c Release --no-build
