name: FileHashGenerator
on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/**'
jobs:
  build:
    name: 🛠️ Build and test
    runs-on: windows-latest
    steps:
    - name: 🔖 Check-out
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: ⚙️ Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10'

    - name: 🛠️ Build x64
      run: dotnet publish ./src/FileHashGenerator/FileHashGenerator.slnx -c Release /p:Platform=x64

    - name: 🛠️ Build arm64
      run: dotnet publish ./src/FileHashGenerator/FileHashGenerator.slnx -c Release /p:Platform=arm64

    - name: 🕵️ Test
      run: |
        cd ./src/FileHashGenerator
        dotnet test --solution ./FileHashGenerator.slnx --coverage
